### ISSUE TITLE
Install/Launch not working on Ubuntu 14.04.

### ISSUE THREAD

**Issue by stevenmcastano** [nfarina/homebridge#347]
root@APPDEV001:/opt/apps/homebridge# npm run start

> homebridge@0.1.1 start /opt/apps/homebridge
> DEBUG=\* node app.js || true

module.js:338
    throw err;
          ^
Error: Cannot find module 'node-persist'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/apps/homebridge/app.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
root@APPDEV001:/opt/apps/homebridge# node -v
v0.12.0
root@APPDEV001:/opt/apps/homebridge# npm -v
2.5.1

I can't seem to get the base server to launch. I've tried to install node-persist both globally and locally.

Any ideas?

**Comment by mignlou** [comment]
I finally got it working on a virtual ubuntu 15.04. Here are the notes I took. They are pieced together from artiicles online. The most helpful was http://www.automatedhome.co.uk/apple/smartthings-raspberry-pi-homebridge-siri-homekit-controlled-smart-home.html. They're not the neatest but its all the commands I ran to have Siri / Homekit work with smartthings. Good luck


Homebridge smartthings Ubuntu 12/17/2015
sudo apt-get update
sudo apt-get upgrade
wget https://nodejs.org/dist/v5.3.0/node-v5.3.0-linux-x86.tar.gz
tar -xvf node-v5.3.0-linux-x86.tar.gz
cd node-v5.3.0-linux-x86
sudo cp -R * /usr/local/
node -v
	"v.5.3.0"
npm -v
	"v.3.3.12"
cd
sudo apt-get install git
sudo apt-get install libavahi-compat-libdnssd-dev 
sudo npm install -g homebridge
sudo npm install -g homebridge-legacy-plugins
homebridge
	"Couldn't find a config.json file [snip]"
	"Added config.json to ./homebridge folder. SUCCESS!!!"

**Comment by Kevin1248** [comment]
migniou -

I followed your instructions, but when i do   node -v   I get the message:
kevin@HP-COMPUTER:~/node-v5.3.0-linux-x86$ node -v
bash: /usr/local/bin/node: No such file or directory
kevin@HP-COMPUTER:~/node-v5.3.0-linux-x86$ 


I verified that the file node is definitely in directory /usr/local/bin:
kevin@HP-COMPUTER:/usr/local/bin$ ls -la
total 22972
drwxr-xr-x  2 root root     4096 Jan  2 11:25 .
drwxr-xr-x 10 root root     4096 Jan  2 11:14 ..
-rwxr-xr-x  1 root root 23512004 Jan  2 11:14 node
lrwxrwxrwx  1 root root       38 Jan  2 11:14 npm -> ../lib/node_modules/npm/bin/npm-cli.js
kevin@HP-COMPUTER:/usr/local/bin$ 

I'm pretty new to Linux - what am I doing wrong?

**Comment by stanthewizzard** [comment]
For the node part
far easier

curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs

node -v
"v.5.3.0"
npm -v
"v.3.3.12"


;)

**Comment by pilot76103** [comment]
stanthewizzard, thank you for your instructions, from a fresh Ubuntu 15 Server to a fully working HomeBridge thanks to you!

**Comment by mignlou** [comment]
Im glad you go it working. I can barely get by in Linux and had a hard time getting it working for me. Mostly because of my lack of Linux knowledge. Once I had it working, I just wanted to share my steps, the same way others have shared theirs to help me out.

**Comment by pilot76103** [comment]
mignlou, my steps were as follows below for Ubuntu 15 Server as a console install only.

1. Install Ubuntu 15 Server with no additional addons.
2. "sudo apt-get update".
3. Install "libavahi-compat-libdnssd-dev" by using "sudo apt-get install -y libavahi-compat-libdnssd-dev".
4. Install Python by using "sudo apt-get install -y python".
5. Install NodeJS and NPM by doing "curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -" followed by "sudo apt-get install -y nodejs".
6. Confirm NodeJS and NPM versions "node -v" should return "v.5.3.0" and "npm -v" should return "v.3.3.12".
7. Install HomeBridge "sudo npm install -g homebridge".
8. Install any needed HomeBridge plugins. For Example "sudo npm install -g homebridge-nest".
9. Configure config.json file "sudo vi ./.homebridge/config.json".
10. Test HomeBridge by running "homebridge".
11. After verifying it's working you can now fully update your Linux distro. "sudo apt-get update", "sudo apt-get -y upgrade" and "sudo apt-get dist-upgrade".

Enjoy!

**Comment by abrazier** [comment]
@pilot76103 I followed your steps and I receive the following:

root@ubuntu:/$ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
No plugins found. See the README for information on installing plugins.
Couldn't find a config.json file at '/home/root/.homebridge/config.json'. Look at config-sample.json for examples of how to format your config.js and add your home accessories.

Are the warnings an issue? Seems like everything installed fine with the exception of those warnings.

**Comment by pilot76103** [comment]
Abrazier,
    It appears you didn't install any plugins or configure the config.json file. The warnings themselves are normal though.

Thanks,
            Jordan Jacob
